### PR TITLE
fix warning for elixir 1.3, fixes #232

### LINKED ISSUE #232: Need to fix warnings for elixir 1.3
When we use the latest elixir version, we have a lot of warnings from tirexs on compilation stage. What do you think about this? I think I can help you to fix it at this week

### PR DESCRIPTION
**Pull request by loganhenson**
Hope the pattern match style for options is ok! Clears all warning 😄

### CODE REVIEW

**Comment by Zatvobor** [comment]
Awesome. Will handle it

File: lib/tirexs/query.ex [hunk 1]
```diff
@@ -11,11 +11,15 @@ defmodule Tirexs.Query do
...
-  def _query(options, query_opts\\[]) do
-    if is_list(options) do
-      query_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def _query(options, query_opts \\ [])
+
+  @doc false
+  def _query(options, _query_opts) when is_list(options) do
+    [query: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: needs use variables, 
`options = extract_do(options, 1)`
`query_opts = Enum.fetch!(options, 0)`
`[query: extract(options) ++ query_opts]`

File: lib/tirexs/query.ex [hunk 2]
```diff
@@ -80,11 +84,15 @@ defmodule Tirexs.Query do
...
-  def boosting(options, boosting_opts\\[]) do
-    if is_list(options) do
-      boosting_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def boosting(options, boosting_opts \\ [])
+
+  @doc false
+  def boosting(options, _boosting_opts) when is_list(options) do
+    [boosting: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: same, please use variables.

File: lib/tirexs/query.ex [hunk 3]
```diff
@@ -101,38 +109,54 @@ defmodule Tirexs.Query do
...
-  def custom_score(options, custom_score_opts\\[]) do
-    if is_list(options) do
-      custom_score_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def custom_score(options, custom_score_opts \\ [])
+
+  @doc false
+  def custom_score(options, _custom_score_opts) when is_list(options) do
+    [custom_score: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: same

File: lib/tirexs/query.ex [hunk 4]
```diff
@@ -101,38 +109,54 @@ defmodule Tirexs.Query do
...
-  def custom_boost_factor(options, custom_boost_factor_opts\\[]) do
-    if is_list(options) do
-      custom_boost_factor_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def custom_boost_factor(options, custom_boost_factor_opts \\ [])
+
+  @doc false
+  def custom_boost_factor(options, _custom_boost_factor_opts) when is_list(options) do
+    [custom_boost_factor: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: same

File: lib/tirexs/query.ex [hunk 5]
```diff
@@ -101,38 +109,54 @@ defmodule Tirexs.Query do
...
+  end
+
+  @doc false
+  def custom_boost_factor(options, custom_boost_factor_opts) do
     [custom_boost_factor: extract(options) ++ custom_boost_factor_opts]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: love it!

File: lib/tirexs/query.ex [hunk 6]
```diff
@@ -101,38 +109,54 @@ defmodule Tirexs.Query do
...
-  def constant_score(options, constant_score_opts\\[]) do
-    if is_list(options) do
-      constant_score_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def constant_score(options, constant_score_opts \\ [])
+
+  @doc false
+  def constant_score(options, _constant_score_opts) when is_list(options) do
+    [constant_score: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: use vars.

File: lib/tirexs/query.ex [hunk 7]
```diff
@@ -101,38 +109,54 @@ defmodule Tirexs.Query do
...
-  def dis_max(options, dis_max_opts\\[]) do
-    if is_list(options) do
-      dis_max_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def dis_max(options, dis_max_opts \\ [])
+
+  @doc false
+  def dis_max(options, _dis_max_opts) when is_list(options) do
+    [dis_max: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: use vars.

File: lib/tirexs/query.ex [hunk 8]
```diff
@@ -173,20 +197,28 @@ defmodule Tirexs.Query do
...
-  def has_child(options, has_child_opts\\[]) do
-    if is_list(options) do
-      has_child_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def has_child(options, has_child_opts \\ [])
+
+  @doc false
+  def has_child(options, _has_child_opts) when is_list(options) do
+    [has_child: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: use vars.

File: lib/tirexs/query.ex [hunk 9]
```diff
@@ -173,20 +197,28 @@ defmodule Tirexs.Query do
...
-  def has_parent(options, has_parent_opts\\[]) do
-    if is_list(options) do
-      has_parent_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def has_parent(options, has_parent_opts \\ [])
+
+  @doc false
+  def has_parent(options, _has_parent_opts) when is_list(options) do
+    [has_parent: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: use vars.

File: lib/tirexs/query.ex [hunk 10]
```diff
@@ -214,11 +246,15 @@ defmodule Tirexs.Query do
...
-  def span_first(options, span_first_opts\\[]) do
-    if is_list(options) do
-      span_first_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def span_first(options, span_first_opts \\ [])
+
+  @doc false
+  def span_first(options, _span_first_opts) when is_list(options) do
+    [span_first: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: use vars.

File: lib/tirexs/query.ex [hunk 11]
```diff
@@ -229,29 +265,41 @@ defmodule Tirexs.Query do
...
-  def span_near(options, span_near_opts\\[]) do
-    if is_list(options) do
-      span_near_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def span_near(options, span_near_opts \\ [])
+
+  @doc false
+  def span_near(options, _span_near_opts) when is_list(options) do
+    [span_near: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: use vars

File: lib/tirexs/query.ex [hunk 12]
```diff
@@ -229,29 +265,41 @@ defmodule Tirexs.Query do
...
-  def span_not(options, span_not_opts\\[]) do
-    if is_list(options) do
-      span_not_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def span_not(options, span_not_opts \\ [])
+
+  @doc false
+  def span_not(options, _span_not_opts) when is_list(options) do
+    [span_not: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: use vars

File: lib/tirexs/query.ex [hunk 13]
```diff
@@ -229,29 +265,41 @@ defmodule Tirexs.Query do
...
-  def span_or(options, span_or_opts\\[]) do
-    if is_list(options) do
-      span_or_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def span_or(options, span_or_opts \\ [])
+
+  @doc false
+  def span_or(options, _span_or_opts) when is_list(options) do
+    [span_or: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: use vars

File: lib/tirexs/query.ex [hunk 14]
```diff
@@ -262,11 +310,15 @@ defmodule Tirexs.Query do
...
-  def top_children(options, top_children_opts\\[]) do
-    if is_list(options) do
-      top_children_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def top_children(options, top_children_opts \\ [])
+
+  @doc false
+  def top_children(options, _top_children_opts) when is_list(options) do
+    [top_children: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: use vars

File: lib/tirexs/query.ex [hunk 15]
```diff
@@ -277,11 +329,15 @@ defmodule Tirexs.Query do
...
-  def indices(options, indices_opts\\[]) do
-    if is_list(options) do
-      indices_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def indices(options, indices_opts \\ [])
+
+  @doc false
+  def indices(options, _indices_opts) when is_list(options) do
+    [indices: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: use vars

File: lib/tirexs/query.ex [hunk 16]
```diff
@@ -292,51 +348,80 @@ defmodule Tirexs.Query do
...
-  def geo_shape(options, geo_shape_opts\\[]) do
-    if is_list(options) do
-      geo_shape_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def geo_shape(options, geo_shape_opts \\ [])
+
+  @doc false
+  def geo_shape(options, _geo_shape_opts) when is_list(options) do
+    [geo_shape: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: use vars please

File: lib/tirexs/query.ex [hunk 17]
```diff
@@ -292,51 +348,80 @@ defmodule Tirexs.Query do
...
-  def nested(options, nested_opts\\[]) do
-    if is_list(options) do
-      nested_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def nested(options, nested_opts \\ [])
+
+  @doc false
+  def nested(options, _nested_opts) when is_list(options) do
+    [nested: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: use vars please

File: lib/tirexs/query.ex [hunk 18]
```diff
@@ -292,51 +348,80 @@ defmodule Tirexs.Query do
...
-  def facet_filter(options, facet_opts\\[]) do
-    if is_list(options) do
-      facet_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def facet_filter(options, facet_opts \\ [])
+
+  @doc false
+  def facet_filter(options, _facet_opts) when is_list(options) do
+    [facet_filter: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: use vars please

File: lib/tirexs/query.ex [hunk 19]
```diff
@@ -292,51 +348,80 @@ defmodule Tirexs.Query do
...
+  def custom_filters_score(options, _custom_filters_score_opts) when is_list(options) do
+    custom_filters_score_opts = Enum.fetch!(options, 0)
+    options = extract_do(options, 1)
+
     custom_filters_score = extract(options) ++ custom_filters_score_opts
     query = [query: custom_filters_score[:query]]
     filters = custom_filters_score[:filters]
     query = Keyword.put(query, :filters, without_array(filters, []))
+
+    [custom_filters_score: query ++ custom_filters_score_opts]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: cool!

File: lib/tirexs/query.ex [hunk 20]
```diff
@@ -391,11 +480,15 @@ defmodule Tirexs.Query do
...
-  def location(options, location_opts\\[]) do
-    if is_list(options) do
-      location_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def location(options, location_opts \\ [])
+
+  @doc false
+  def location(options, _location_opts) when is_list(options) do
+    [location: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query.ex]: use vars please

File: lib/tirexs/query/filter.ex [hunk 21]
```diff
@@ -11,11 +11,15 @@ defmodule Tirexs.Query.Filter do
...
-  def _filter(options, filter_opts \\ []) do
-    if is_list(options) do
-      filter_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def _filter(options, filter_opts \\ [])
+
+  @doc false
+  def _filter(options, _filter_opts) when is_list(options) do
+    [filter: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query/filter.ex]: use vars please

File: lib/tirexs/query/filter.ex [hunk 22]
```diff
@@ -64,11 +72,15 @@ defmodule Tirexs.Query.Filter do
...
-  def fquery(options, fquery_opts \\ []) do
-    if is_list(options) do
-      fquery_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def fquery(options, fquery_opts \\ [])
+
+  @doc false
+  def fquery(options, _fquery_opts) when is_list(options) do
+    [fquery: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query/filter.ex]: use vars please

File: lib/tirexs/query/filter.ex [hunk 23]
```diff
@@ -84,20 +96,28 @@ defmodule Tirexs.Query.Filter do
...
-  def _and(options, and_opts \\ []) do
-    if is_list(options) do
-      and_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def _and(options, and_opts \\ [])
+
+  @doc false
+  def _and(options, _and_opts) when is_list(options) do
+    [and: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query/filter.ex]: use vars please

File: lib/tirexs/query/filter.ex [hunk 24]
```diff
@@ -84,20 +96,28 @@ defmodule Tirexs.Query.Filter do
...
-  def _or(options, or_opts \\ []) do
-    if is_list(options) do
-      or_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def _or(options, or_opts \\ [])
+
+  @doc false
+  def _or(options, _or_opts) when is_list(options) do
+    [or: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/query/filter.ex]: use vars please

File: lib/tirexs/search.ex [hunk 25]
```diff
@@ -96,15 +96,18 @@ defmodule Tirexs.Search do
 
   @doc false
   def extract_index_options(options, index_opts \\ []) do
-    if options[:index] do
-      index_opts = index_opts ++ [index: options[:index]]
-      options = Keyword.delete(options, :index)
+    [options, index_opts] = if options[:index] do
+      [Keyword.delete(options, :index), index_opts ++ [index: options[:index]]]
```
Comment (OpakAlex) [inline lib/tirexs/search.ex]: use vars please

File: lib/tirexs/search.ex [hunk 26]
```diff
@@ -96,15 +96,18 @@ defmodule Tirexs.Search do
...
+    else
+      [options, index_opts]
     end
 
-    if options[:type] do
-      index_opts = index_opts ++ [type: options[:type]]
-      options = Keyword.delete(options, :type)
+    [options, index_opts] = if options[:type] do
+      [Keyword.delete(options, :type), index_opts ++ [type: options[:type]]]
```
Comment (OpakAlex) [inline lib/tirexs/search.ex]: use vars please

File: lib/tirexs/search/rescore.ex [hunk 27]
```diff
@@ -28,11 +28,15 @@ defmodule Tirexs.Search.Rescore do
...
-  def _rescore(options, rescore_opts \\ []) do
-    if is_list(options) do
-      rescore_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def _rescore(options, rescore_opts \\ [])
+
+  @doc false
+  def _rescore(options, _rescore_opts) when is_list(options) do
+    [rescore: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/search/rescore.ex]: use vars please

File: lib/tirexs/search/suggest.ex [hunk 28]
```diff
@@ -29,23 +29,30 @@ defmodule Tirexs.Search.Suggest do
...
-  def _suggest(options, suggest_opts \\ []) do
-    if is_list(options) do
-      suggest_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def _suggest(options, suggest_opts \\ [])
+
+  @doc false
+  def _suggest(options, _suggest_opts) when is_list(options) do
+    [suggest: extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/search/suggest.ex]: use vars please

File: lib/tirexs/search/suggest.ex [hunk 29]
```diff
@@ -29,23 +29,30 @@ defmodule Tirexs.Search.Suggest do
...
-    if is_list(options) do
-      suggest_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
-      routers(name, options, suggest_opts)
+  def make_suggest(name, options, suggest_opts \\ [])
+
+  @doc false
+  def make_suggest(name, options, _suggest_opts) when is_list(options) do
+    routers(name, extract_do(options, 1), Enum.fetch!(options, 0))
```
Comment (OpakAlex) [inline lib/tirexs/search/suggest.ex]: use vars please

File: lib/tirexs/search/warmer.ex [hunk 30]
```diff
@@ -21,22 +21,25 @@ defmodule Tirexs.Search.Warmer do
...
 
-  def make_warmer(name, options, warmers_opts \\ []) do
-    if is_list(options) do
-      warmers_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
+  def make_warmer(name, options, warmers_opts \\ [])
+
+  def make_warmer(name, options, _warmers_opts) when is_list(options) do
+    Keyword.put([], to_atom(name), routers(name, extract_do(options, 1), []) ++ Enum.fetch!(options, 0))
```
Comment (OpakAlex) [inline lib/tirexs/search/warmer.ex]: use vars please, because i can not read this line.

File: lib/tirexs/search/warmer.ex [hunk 31]
```diff
@@ -21,22 +21,25 @@ defmodule Tirexs.Search.Warmer do
...
-  def source(options, source_opts \\ []) do
-    if is_list(options) do
-      source_opts = Enum.fetch!(options, 0)
-      options = extract_do(options, 1)
-    end
-    [source:  extract(options) ++ source_opts]
+  def source(options, source_opts \\ [])
+
+  def source(options, _source_opts) when is_list(options) do
+    [source:  extract(extract_do(options, 1)) ++ Enum.fetch!(options, 0)]
```
Comment (OpakAlex) [inline lib/tirexs/search/warmer.ex]: use vars please

**Comment by OpakAlex** [comment]
@loganhenson great work man!
Use please project code style.

**Comment by Zatvobor** [comment]
Amazing. Thanks @OpakAlex.

**Comment by loganhenson** [comment]
Sorry about that guys, should I fix it or are one of you?

**Comment by OpakAlex** [comment]
@loganhenson i think you can fix it in 1 hour max :) and then we will merge!

File: lib/tirexs/query.ex (hunk 1 above)
Comment (loganhenson) [inline lib/tirexs/query.ex]: This actually will not compile, because options is mutated, if vars it must be:
```
query_opts = Enum.fetch!(options, 0)
options = extract_do(options, 1)
[query: extract(options) ++ query_opts]
```

no issue though

Comment (OpakAlex) [inline lib/tirexs/query.ex]: yes, i think about readable code. If we use variables, it's more easy understand what happens in this line. But when i see big lines, it's so hard. Tirexs code so open for new developers, and elixir new language, we need make code easy as possible. It's Tirexs idea.

Comment (loganhenson) [inline lib/tirexs/query.ex]: No problem my man

**Comment by loganhenson** [comment]
Should be good to go

**Comment by OpakAlex** [comment]
@loganhenson thanks man!
